/**
 * Fiche SEO par article — formation Blogging & SEO (Qualiopi).
 * - intent : informationnelle | commerciale | transactionnelle | navigationnelle
 * - primary + 2 secondary + longue traîne
 * - candidateQueries : requêtes élargies (PAA, variantes, local)
 * - contentFormat : format éditorial aligné sur l'intention
 */
module.exports = {
  "5-points-controle-avant-ct-ivry": {
    intent: "informational",
    contentFormat: "Checklist pratique",
    primary: "contrôle technique Ivry",
    secondary: ["checklist contrôle technique","préparer voiture CT"],
    longTail: "5 points à vérifier avant contrôle technique 94",
    candidateQueries: [
      "contrôle technique Ivry",
      "checklist contrôle technique",
      "préparer voiture CT",
      "5 points à vérifier avant contrôle technique 94",
      "points contrôle technique avant CT",
      "liste contrôle technique 2026",
      "comment préparer contrôle technique Ivry",
      "que vérifier avant CT garage 94",
    ],
  },
  "adblue-voyant-panne-diesel": {
    intent: "informational",
    contentFormat: "Guide symptômes — signes, causes, que faire",
    primary: "voyant AdBlue allumé",
    secondary: ["panne AdBlue diesel","système SCR diesel"],
    longTail: "que faire voyant AdBlue diesel Euro 6",
    candidateQueries: [
      "voyant AdBlue allumé",
      "panne AdBlue diesel",
      "que faire voyant AdBlue diesel Euro 6",
      "recharge AdBlue garage 94",
      "autonomie AdBlue restante",
      "AdBlue plein voyant allumé",
      "système SCR panne diesel",
      "voyant AdBlue refus démarrage",
    ],
  },
  "alternateur-hs-symptomes": {
    intent: "informational",
    contentFormat: "Guide symptômes — signes, causes, que faire",
    primary: "alternateur HS symptômes",
    secondary: ["panne alternateur voiture","voyant batterie allumé"],
    longTail: "comment savoir si alternateur est mort",
    candidateQueries: [
      "alternateur HS symptômes",
      "panne alternateur voiture",
      "voyant batterie allumé",
      "comment savoir si alternateur est mort",
      "alternateur à changer Ivry",
      "comment reconnaître alternateur HS",
      "alternateur HS symptômes causes",
      "panne alternateur voiture alternateur HS symptômes",
    ],
  },
  "amortisseurs-usures-symptomes": {
    intent: "informational",
    contentFormat: "Guide symptômes — signes, causes, que faire",
    primary: "amortisseurs usés symptômes",
    secondary: ["usure amortisseur voiture","tenue de route amortisseurs"],
    longTail: "quand changer amortisseurs avant arrière",
    candidateQueries: [
      "amortisseurs usés symptômes",
      "usure amortisseur voiture",
      "tenue de route amortisseurs",
      "quand changer amortisseurs avant arrière",
      "amortisseurs fatigués bruit",
      "comment reconnaître amortisseurs usés",
      "amortisseurs usés symptômes causes",
      "usure amortisseur voiture amortisseurs usés symptômes",
    ],
  },
  "batterie-morte-matin-que-faire": {
    intent: "informational",
    contentFormat: "Guide pratique — causes, que faire, retour atelier",
    primary: "batterie morte le matin que faire",
    secondary: ["voiture ne démarre pas froid","batterie voiture déchargée"],
    longTail: "batterie à plat au réveil que faire",
    candidateQueries: [
      "batterie morte le matin que faire",
      "voiture ne démarre pas froid",
      "batterie voiture déchargée",
      "batterie à plat au réveil que faire",
      "dépannage batterie Ivry 94",
      "batterie morte le matin que faire ?",
      "voiture ne démarre pas froid batterie morte le",
      "batterie morte le matin que faire garage",
    ],
  },
  "batterie-start-stop-usure-prematuree": {
    intent: "informational",
    contentFormat: "Guide pratique — causes, que faire, retour atelier",
    primary: "batterie start-stop usure",
    secondary: ["batterie AGM start stop","durée vie batterie start stop"],
    longTail: "batterie start stop usée trop vite",
    candidateQueries: [
      "batterie start-stop usure",
      "batterie AGM start stop",
      "durée vie batterie start stop",
      "batterie start stop usée trop vite",
      "changer batterie start stop 94",
      "batterie start-stop usure : que faire",
      "comment batterie start-stop usure",
      "batterie AGM start stop batterie start-stop usure",
    ],
  },
  "batterie-voiture-quand-changer": {
    intent: "informational",
    contentFormat: "Guide entretien — fréquence et critères",
    primary: "quand changer batterie voiture",
    secondary: ["durée vie batterie auto","signes batterie faible"],
    longTail: "batterie voiture combien d'années",
    candidateQueries: [
      "quand changer batterie voiture",
      "durée vie batterie auto",
      "signes batterie faible",
      "batterie voiture combien d'années",
      "remplacement batterie garage Ivry",
      "quand changer batterie voiture ?",
      "durée vie batterie auto quand changer batterie",
      "quand changer batterie voiture garage",
    ],
  },
  "bougies-allumage-quand-changer": {
    intent: "informational",
    contentFormat: "Guide entretien — fréquence et critères",
    primary: "bougies d'allumage quand changer",
    secondary: ["intervalle changement bougies","bougies usées symptômes"],
    longTail: "bougies essence à changer tous les combien km",
    candidateQueries: [
      "bougies d'allumage quand changer",
      "intervalle changement bougies",
      "bougies usées symptômes",
      "bougies essence à changer tous les combien km",
      "bougies moteur ratés allumage",
      "bougies d'allumage quand changer ?",
      "intervalle changement bougies bougies d'allumage quand",
      "bougies d'allumage quand changer garage",
    ],
  },
  "bruit-anormal-voiture-que-faire": {
    intent: "informational",
    contentFormat: "Guide symptômes — signes, causes, que faire",
    primary: "bruit anormal voiture que faire",
    secondary: ["bruit moteur suspension","diagnostic bruit auto"],
    longTail: "bruit au freinage ou accélération que faire",
    candidateQueries: [
      "bruit anormal voiture que faire",
      "bruit moteur suspension",
      "diagnostic bruit auto",
      "bruit au freinage ou accélération que faire",
      "identifier bruit voiture garage",
      "bruit anormal voiture que faire ?",
      "bruit moteur suspension bruit anormal voiture",
      "bruit anormal voiture que faire garage",
    ],
  },
  "cardan-qui-claque-causes": {
    intent: "informational",
    contentFormat: "Guide pratique — causes, que faire, retour atelier",
    primary: "cardan qui claque",
    secondary: ["joint cardan usé","bruit cardan virage"],
    longTail: "cardan claque en braquant causes",
    candidateQueries: [
      "cardan qui claque",
      "joint cardan usé",
      "bruit cardan virage",
      "cardan claque en braquant causes",
      "remplacement cardan prix 94",
      "cardan qui claque : que faire",
      "comment cardan qui claque",
      "joint cardan usé cardan qui claque",
    ],
  },
  "catalyseur-bouche-symptomes-causes": {
    intent: "informational",
    contentFormat: "Guide symptômes — signes, causes, que faire",
    primary: "catalyseur bouché symptômes",
    secondary: ["panne catalyseur voiture","perte puissance catalyseur"],
    longTail: "catalyseur encrassé que faire",
    candidateQueries: [
      "catalyseur bouché symptômes",
      "panne catalyseur voiture",
      "perte puissance catalyseur",
      "catalyseur encrassé que faire",
      "catalyseur à changer diesel",
      "comment reconnaître catalyseur bouché",
      "catalyseur bouché symptômes causes",
      "panne catalyseur voiture catalyseur bouché symptômes",
    ],
  },
  "clim-odeur-moisi-que-faire": {
    intent: "informational",
    contentFormat: "Guide pratique — causes, que faire, retour atelier",
    primary: "climatisation odeur moisi",
    secondary: ["odeur humidité clim voiture","nettoyage évaporateur clim"],
    longTail: "clim sent mauvais que faire",
    candidateQueries: [
      "climatisation odeur moisi",
      "odeur humidité clim voiture",
      "nettoyage évaporateur clim",
      "clim sent mauvais que faire",
      "désinfection climatisation auto Ivry",
      "climatisation odeur moisi : que faire",
      "comment climatisation odeur moisi",
      "odeur humidité clim voiture climatisation odeur moisi",
    ],
  },
  "climatisation-voiture-recharge-ivry": {
    intent: "transactional",
    contentFormat: "Guide pratique — causes, que faire, retour atelier",
    primary: "recharge climatisation voiture",
    secondary: ["clim ne refroidit plus","gaz climatisation auto"],
    longTail: "recharge clim voiture Ivry-sur-Seine",
    candidateQueries: [
      "recharge climatisation voiture",
      "clim ne refroidit plus",
      "gaz climatisation auto",
      "recharge clim voiture Ivry-sur-Seine",
      "prix recharge clim 94",
      "recharge climatisation voiture : que faire",
      "comment recharge climatisation voiture",
      "clim ne refroidit plus recharge climatisation voiture",
    ],
  },
  "combien-coute-vidange-voiture": {
    intent: "commercial",
    contentFormat: "Guide prix — fourchette et prestation",
    primary: "prix vidange voiture",
    secondary: ["combien coûte une vidange","tarif vidange garage"],
    longTail: "prix vidange voiture 2026 France",
    candidateQueries: [
      "prix vidange voiture",
      "combien coûte une vidange",
      "tarif vidange garage",
      "prix vidange voiture 2026 France",
      "vidange garage indépendant 94",
      "combien coûte vidange voiture",
      "prix vidange voiture 2026",
      "combien coûte une vidange prix vidange voiture",
    ],
  },
  "combien-temps-entre-deux-vidanges": {
    intent: "informational",
    contentFormat: "Guide entretien — fréquence et critères",
    primary: "intervalle entre deux vidanges",
    secondary: ["fréquence vidange voiture","vidange tous les combien km"],
    longTail: "combien de km entre deux vidanges",
    candidateQueries: [
      "intervalle entre deux vidanges",
      "fréquence vidange voiture",
      "vidange tous les combien km",
      "combien de km entre deux vidanges",
      "vidange annuelle obligatoire",
      "intervalle entre deux vidanges : que faire",
      "comment intervalle entre deux vidanges",
      "fréquence vidange voiture intervalle entre deux",
    ],
  },
  "compresseur-clim-mort-symptomes": {
    intent: "informational",
    contentFormat: "Guide symptômes — signes, causes, que faire",
    primary: "compresseur clim mort symptômes",
    secondary: ["panne compresseur climatisation","clim plus de froid"],
    longTail: "compresseur clim HS bruit",
    candidateQueries: [
      "compresseur clim mort symptômes",
      "panne compresseur climatisation",
      "clim plus de froid",
      "compresseur clim HS bruit",
      "changer compresseur clim prix",
      "comment reconnaître compresseur clim mort",
      "compresseur clim mort symptômes causes",
      "panne compresseur climatisation compresseur clim mort",
    ],
  },
  "consommation-huile-anormale-causes": {
    intent: "informational",
    contentFormat: "Guide pratique — causes, que faire, retour atelier",
    primary: "consommation huile anormale",
    secondary: ["voiture consomme de l'huile","niveau huile baisse"],
    longTail: "consommation huile excessive causes moteur",
    candidateQueries: [
      "consommation huile anormale",
      "voiture consomme de l'huile",
      "niveau huile baisse",
      "consommation huile excessive causes moteur",
      "huile moteur qui disparaît",
      "consommation huile anormale : que faire",
      "comment consommation huile anormale",
      "voiture consomme de l'huile consommation huile anormale",
    ],
  },
  "controle-antipollution-refuse-que-faire": {
    intent: "informational",
    contentFormat: "Guide pratique — causes, que faire, retour atelier",
    primary: "contrôle antipollution refusé que faire",
    secondary: ["visite antipollution contre-visite","pollution CT refus"],
    longTail: "contre-visite antipollution que faire",
    candidateQueries: [
      "contrôle antipollution refusé que faire",
      "visite antipollution contre-visite",
      "pollution CT refus",
      "contre-visite antipollution que faire",
      "réparer pour antipollution 94",
      "contrôle antipollution refusé que faire ?",
      "visite antipollution contre-visite contrôle antipollution refusé",
      "contrôle antipollution refusé que faire garage",
    ],
  },
  "controle-technique-2026-nouveautes": {
    intent: "informational",
    contentFormat: "Guide pratique — causes, que faire, retour atelier",
    primary: "contrôle technique 2026 nouveautés",
    secondary: ["nouveau contrôle technique 2026","règlement CT 2026"],
    longTail: "changements contrôle technique 2026 France",
    candidateQueries: [
      "contrôle technique 2026 nouveautés",
      "nouveau contrôle technique 2026",
      "règlement CT 2026",
      "changements contrôle technique 2026 France",
      "CT 2026 ce qui change",
      "contrôle technique 2026 nouveautés : que faire",
      "comment contrôle technique 2026 nouveautés",
      "nouveau contrôle technique 2026 contrôle technique 2026",
    ],
  },
  "courroie-accessoires-symptomes-usure": {
    intent: "informational",
    contentFormat: "Guide symptômes — signes, causes, que faire",
    primary: "courroie accessoires usée symptômes",
    secondary: ["courroie alternateur usure","bruit courroie accessoires"],
    longTail: "quand changer courroie accessoires",
    candidateQueries: [
      "courroie accessoires usée symptômes",
      "courroie alternateur usure",
      "bruit courroie accessoires",
      "quand changer courroie accessoires",
      "courroie accessoires cassée",
      "comment reconnaître courroie accessoires usée",
      "courroie accessoires usée symptômes causes",
      "courroie alternateur usure courroie accessoires usée",
    ],
  },
  "courroie-distribution-quand-changer-94": {
    intent: "informational",
    contentFormat: "Guide entretien — fréquence et critères",
    primary: "courroie distribution quand changer",
    secondary: ["kit distribution intervalle","courroie distribution cassée"],
    longTail: "changement courroie distribution 94 prix",
    candidateQueries: [
      "courroie distribution quand changer",
      "kit distribution intervalle",
      "courroie distribution cassée",
      "changement courroie distribution 94 prix",
      "distribution tous les combien km",
      "courroie distribution quand changer ?",
      "kit distribution intervalle courroie distribution quand",
      "courroie distribution quand changer Ivry-sur-Seine",
    ],
  },
  "crevaison-reparer-ou-changer-pneu": {
    intent: "informational",
    contentFormat: "Guide pratique — causes, que faire, retour atelier",
    primary: "crevaison réparer ou changer pneu",
    secondary: ["réparation pneu crevé","pneu hors service"],
    longTail: "crevaison clou réparable ou pas",
    candidateQueries: [
      "crevaison réparer ou changer pneu",
      "réparation pneu crevé",
      "pneu hors service",
      "crevaison clou réparable ou pas",
      "changer pneu après crevaison",
      "crevaison réparer ou changer pneu : que faire",
      "comment crevaison réparer ou changer pneu",
      "réparation pneu crevé crevaison réparer ou",
    ],
  },
  "debosselage-sans-peinture-dsp": {
    intent: "informational",
    contentFormat: "Guide pratique — causes, que faire, retour atelier",
    primary: "débosselage sans peinture DSP",
    secondary: ["enlever bosse carrosserie","DSP carrosserie"],
    longTail: "débosselage sans peinture prix Ivry",
    candidateQueries: [
      "débosselage sans peinture DSP",
      "enlever bosse carrosserie",
      "DSP carrosserie",
      "débosselage sans peinture prix Ivry",
      "bosse portière sans repeindre",
      "débosselage sans peinture DSP : que faire",
      "comment débosselage sans peinture DSP",
      "enlever bosse carrosserie débosselage sans peinture",
    ],
  },
  "decalaminage-moteur-utile-ou-arnaque": {
    intent: "informational",
    contentFormat: "Guide pratique — causes, que faire, retour atelier",
    primary: "décalaminage moteur utile ou arnaque",
    secondary: ["nettoyage moteur hydrogène","décalaminage diesel"],
    longTail: "décalaminage moteur ça marche vraiment",
    candidateQueries: [
      "décalaminage moteur utile ou arnaque",
      "nettoyage moteur hydrogène",
      "décalaminage diesel",
      "décalaminage moteur ça marche vraiment",
      "hydrogénation moteur avis",
      "décalaminage moteur utile ou arnaque : que faire",
      "comment décalaminage moteur utile ou arnaque",
      "nettoyage moteur hydrogène décalaminage moteur utile",
    ],
  },
  "demarreur-hs-symptomes": {
    intent: "informational",
    contentFormat: "Guide symptômes — signes, causes, que faire",
    primary: "démarreur HS symptômes",
    secondary: ["panne démarreur voiture","voiture clique sans démarrer"],
    longTail: "démarreur mort bruit clic",
    candidateQueries: [
      "démarreur HS symptômes",
      "panne démarreur voiture",
      "voiture clique sans démarrer",
      "démarreur mort bruit clic",
      "changer démarreur prix 94",
      "comment reconnaître démarreur HS",
      "démarreur HS symptômes causes",
      "panne démarreur voiture démarreur HS symptômes",
    ],
  },
  "direction-assistee-dure-grincements": {
    intent: "informational",
    contentFormat: "Guide pratique — causes, que faire, retour atelier",
    primary: "direction assistée dure grincements",
    secondary: ["crissement direction","direction dure à froid"],
    longTail: "direction assistée dure en virage",
    candidateQueries: [
      "direction assistée dure grincements",
      "crissement direction",
      "direction dure à froid",
      "direction assistée dure en virage",
      "liquide direction assistée",
      "direction assistée dure grincements : que faire",
      "comment direction assistée dure grincements",
      "crissement direction direction assistée dure",
    ],
  },
  "disques-frein-voiles-usure-signes": {
    intent: "informational",
    contentFormat: "Guide symptômes — signes, causes, que faire",
    primary: "disques frein voilés usure",
    secondary: ["disque frein usé symptômes","vibration freinage disque"],
    longTail: "disques de frein voilés que faire",
    candidateQueries: [
      "disques frein voilés usure",
      "disque frein usé symptômes",
      "vibration freinage disque",
      "disques de frein voilés que faire",
      "rectifier ou changer disques frein",
      "disques frein voilés usure : que faire",
      "comment disques frein voilés usure",
      "disque frein usé symptômes disques frein voilés",
    ],
  },
  "embrayage-qui-patine-causes": {
    intent: "informational",
    contentFormat: "Guide pratique — causes, que faire, retour atelier",
    primary: "embrayage qui patine",
    secondary: ["embrayage usé symptômes","patine embrayage causes"],
    longTail: "embrayage patine côte causes",
    candidateQueries: [
      "embrayage qui patine",
      "embrayage usé symptômes",
      "patine embrayage causes",
      "embrayage patine côte causes",
      "changer embrayage prix 94",
      "embrayage qui patine : que faire",
      "comment embrayage qui patine",
      "embrayage usé symptômes embrayage qui patine",
    ],
  },
  "entretien-voiture-eviter-pannes-ivry": {
    intent: "transactional",
    contentFormat: "Guide pratique — causes, que faire, retour atelier",
    primary: "entretien voiture éviter pannes",
    secondary: ["entretien préventif auto","révision entretien courant"],
    longTail: "entretien voiture Ivry-sur-Seine",
    candidateQueries: [
      "entretien voiture éviter pannes",
      "entretien préventif auto",
      "révision entretien courant",
      "entretien voiture Ivry-sur-Seine",
      "éviter panne voiture usage ville",
      "entretien voiture éviter pannes : que faire",
      "comment entretien voiture éviter pannes",
      "entretien préventif auto entretien voiture éviter",
    ],
  },
  "fap-dpf-encrasse-trajets-ville": {
    intent: "informational",
    contentFormat: "Guide pratique — causes, que faire, retour atelier",
    primary: "FAP DPF encrassé trajets ville",
    secondary: ["filtre particules bouché","régénération FAP"],
    longTail: "FAP encrassé conduite urbaine que faire",
    candidateQueries: [
      "FAP DPF encrassé trajets ville",
      "filtre particules bouché",
      "régénération FAP",
      "FAP encrassé conduite urbaine que faire",
      "nettoyage FAP diesel 94",
      "FAP DPF encrassé trajets ville : que faire",
      "comment FAP DPF encrassé trajets ville",
      "filtre particules bouché FAP DPF encrassé",
    ],
  },
  "filtre-gasoil-quand-changer": {
    intent: "informational",
    contentFormat: "Guide entretien — fréquence et critères",
    primary: "filtre gasoil quand changer",
    secondary: ["filtre à carburant diesel","intervalle filtre gasoil"],
    longTail: "changer filtre gasoil tous les combien km",
    candidateQueries: [
      "filtre gasoil quand changer",
      "filtre à carburant diesel",
      "intervalle filtre gasoil",
      "changer filtre gasoil tous les combien km",
      "filtre gasoil bouché symptômes",
      "filtre gasoil quand changer ?",
      "filtre à carburant diesel filtre gasoil quand",
      "filtre gasoil quand changer garage",
    ],
  },
  "filtre-habitacle-pollen-quand-changer": {
    intent: "informational",
    contentFormat: "Guide entretien — fréquence et critères",
    primary: "filtre habitacle pollen quand changer",
    secondary: ["filtre pollen voiture","filtre climatisation habitacle"],
    longTail: "filtre habitacle à changer fréquence",
    candidateQueries: [
      "filtre habitacle pollen quand changer",
      "filtre pollen voiture",
      "filtre climatisation habitacle",
      "filtre habitacle à changer fréquence",
      "odeur clim filtre pollen",
      "filtre habitacle pollen quand changer ?",
      "filtre pollen voiture filtre habitacle pollen",
      "filtre habitacle pollen quand changer garage",
    ],
  },
  "freinage-mou-pedale-spongieuse": {
    intent: "informational",
    contentFormat: "Guide pratique — causes, que faire, retour atelier",
    primary: "freinage mou pédale spongieuse",
    secondary: ["pédale frein molle","liquide frein air circuit"],
    longTail: "pédale de frein spongieuse causes",
    candidateQueries: [
      "freinage mou pédale spongieuse",
      "pédale frein molle",
      "liquide frein air circuit",
      "pédale de frein spongieuse causes",
      "frein mou dangereux que faire",
      "freinage mou pédale spongieuse : que faire",
      "comment freinage mou pédale spongieuse",
      "pédale frein molle freinage mou pédale",
    ],
  },
  "fuite-huile-moteur-causes-que-faire": {
    intent: "informational",
    contentFormat: "Guide symptômes — signes, causes, que faire",
    primary: "fuite huile moteur causes",
    secondary: ["voiture perd de l'huile","tache huile sous moteur"],
    longTail: "fuite huile moteur que faire urgence",
    candidateQueries: [
      "fuite huile moteur causes",
      "voiture perd de l'huile",
      "tache huile sous moteur",
      "fuite huile moteur que faire urgence",
      "réparer fuite huile garage",
      "fuite huile moteur causes : que faire",
      "comment fuite huile moteur causes",
      "voiture perd de l'huile fuite huile moteur",
    ],
  },
  "fuite-liquide-frein-reconnaitre": {
    intent: "informational",
    contentFormat: "Guide symptômes — signes, causes, que faire",
    primary: "fuite liquide de frein",
    secondary: ["niveau liquide frein bas","reconnaître fuite frein"],
    longTail: "fuite liquide frein symptômes",
    candidateQueries: [
      "fuite liquide de frein",
      "niveau liquide frein bas",
      "reconnaître fuite frein",
      "fuite liquide frein symptômes",
      "liquide frein rouge sous voiture",
      "fuite liquide de frein : que faire",
      "comment fuite liquide de frein",
      "niveau liquide frein bas fuite liquide de",
    ],
  },
  "fumee-blanche-echappement-que-faire": {
    intent: "informational",
    contentFormat: "Guide symptômes — signes, causes, que faire",
    primary: "fumée blanche échappement",
    secondary: ["fumée blanche au démarrage","vapeur échappement"],
    longTail: "fumée blanche échappement que faire",
    candidateQueries: [
      "fumée blanche échappement",
      "fumée blanche au démarrage",
      "vapeur échappement",
      "fumée blanche échappement que faire",
      "fumée blanche joint culasse",
      "fumée blanche échappement : que faire",
      "comment fumée blanche échappement",
      "fumée blanche au démarrage fumée blanche échappement",
    ],
  },
  "fumee-bleue-echappement-causes": {
    intent: "informational",
    contentFormat: "Guide symptômes — signes, causes, que faire",
    primary: "fumée bleue échappement causes",
    secondary: ["voiture fume bleu","consommation huile fumée bleue"],
    longTail: "fumée bleue moteur essence causes",
    candidateQueries: [
      "fumée bleue échappement causes",
      "voiture fume bleu",
      "consommation huile fumée bleue",
      "fumée bleue moteur essence causes",
      "segments moteur fumée bleue",
      "fumée bleue échappement causes : que faire",
      "comment fumée bleue échappement causes",
      "voiture fume bleu fumée bleue échappement",
    ],
  },
  "garage-independant-vs-concessionnaire": {
    intent: "commercial",
    contentFormat: "Comparatif — avantages et limites",
    primary: "garage indépendant vs concessionnaire",
    secondary: ["entretien garage indépendant","révision chez concession"],
    longTail: "garage indépendant ou concessionnaire avantages",
    candidateQueries: [
      "garage indépendant vs concessionnaire",
      "entretien garage indépendant",
      "révision chez concession",
      "garage indépendant ou concessionnaire avantages",
      "prix entretien indépendant 94",
      "garage indépendant vs concessionnaire : que faire",
      "comment garage indépendant vs concessionnaire",
      "entretien garage indépendant garage indépendant vs",
    ],
  },
  "geometrie-roues-signes-mauvais-alignement": {
    intent: "informational",
    contentFormat: "Guide symptômes — signes, causes, que faire",
    primary: "géométrie roues mauvais alignement",
    secondary: ["parallelisme voiture","voiture tire sur un côté"],
    longTail: "signes mauvais parallelisme pneus",
    candidateQueries: [
      "géométrie roues mauvais alignement",
      "parallelisme voiture",
      "voiture tire sur un côté",
      "signes mauvais parallelisme pneus",
      "géométrie roues prix 94",
      "géométrie roues mauvais alignement : que faire",
      "comment géométrie roues mauvais alignement",
      "parallelisme voiture géométrie roues mauvais",
    ],
  },
  "injecteurs-encrasses-symptomes": {
    intent: "informational",
    contentFormat: "Guide symptômes — signes, causes, que faire",
    primary: "injecteurs encrassés symptômes",
    secondary: ["injecteur diesel bouché","perte puissance injecteurs"],
    longTail: "nettoyage injecteurs utile",
    candidateQueries: [
      "injecteurs encrassés symptômes",
      "injecteur diesel bouché",
      "perte puissance injecteurs",
      "nettoyage injecteurs utile",
      "injecteurs encrassés broute",
      "comment reconnaître injecteurs encrassés",
      "injecteurs encrassés symptômes causes",
      "injecteur diesel bouché injecteurs encrassés symptômes",
    ],
  },
  "joint-culasse-signes-symptomes": {
    intent: "informational",
    contentFormat: "Guide symptômes — signes, causes, que faire",
    primary: "joint de culasse symptômes",
    secondary: ["joint culasse HS signes","surchauffe joint culasse"],
    longTail: "comment savoir joint culasse HS",
    candidateQueries: [
      "joint de culasse symptômes",
      "joint culasse HS signes",
      "surchauffe joint culasse",
      "comment savoir joint culasse HS",
      "joint culasse fumée mayonnaise",
      "comment reconnaître joint de culasse",
      "joint de culasse symptômes causes",
      "joint culasse HS signes joint de culasse",
    ],
  },
  "liquide-frein-quand-changer": {
    intent: "informational",
    contentFormat: "Guide entretien — fréquence et critères",
    primary: "liquide de frein quand changer",
    secondary: ["intervalle liquide frein","DOT4 frein"],
    longTail: "changer liquide frein tous les combien",
    candidateQueries: [
      "liquide de frein quand changer",
      "intervalle liquide frein",
      "DOT4 frein",
      "changer liquide frein tous les combien",
      "liquide frein foncé",
      "liquide de frein quand changer ?",
      "intervalle liquide frein liquide de frein",
      "liquide de frein quand changer garage",
    ],
  },
  "liquide-refroidissement-quand-verifier": {
    intent: "informational",
    contentFormat: "Guide entretien — fréquence et critères",
    primary: "liquide refroidissement quand vérifier",
    secondary: ["niveau liquide refroidissement","antigel moteur"],
    longTail: "vérifier liquide refroidissement fréquence",
    candidateQueries: [
      "liquide refroidissement quand vérifier",
      "niveau liquide refroidissement",
      "antigel moteur",
      "vérifier liquide refroidissement fréquence",
      "liquide refroidissement bas",
      "liquide refroidissement quand vérifier ?",
      "niveau liquide refroidissement liquide refroidissement quand",
      "liquide refroidissement quand vérifier garage",
    ],
  },
  "pare-brise-fissure-controle-technique": {
    intent: "informational",
    contentFormat: "Guide pratique — causes, que faire, retour atelier",
    primary: "pare-brise fissure contrôle technique",
    secondary: ["impact pare-brise CT","fissure vitre avant CT"],
    longTail: "pare-brise fissuré refus CT",
    candidateQueries: [
      "pare-brise fissure contrôle technique",
      "impact pare-brise CT",
      "fissure vitre avant CT",
      "pare-brise fissuré refus CT",
      "remplacement pare-brise 94",
      "pare-brise fissure contrôle technique : que faire",
      "comment pare-brise fissure contrôle technique",
      "impact pare-brise CT pare-brise fissure contrôle",
    ],
  },
  "peinture-localisee-retouche-carrosserie": {
    intent: "informational",
    contentFormat: "Guide pratique — causes, que faire, retour atelier",
    primary: "peinture localisée retouche carrosserie",
    secondary: ["retouche peinture auto","rayure peinture réparer"],
    longTail: "retouche peinture aile portière prix",
    candidateQueries: [
      "peinture localisée retouche carrosserie",
      "retouche peinture auto",
      "rayure peinture réparer",
      "retouche peinture aile portière prix",
      "peinture localisée garage Ivry",
      "peinture localisée retouche carrosserie : que faire",
      "comment peinture localisée retouche carrosserie",
      "retouche peinture auto peinture localisée retouche",
    ],
  },
  "perte-puissance-soudaine-causes": {
    intent: "informational",
    contentFormat: "Guide pratique — causes, que faire, retour atelier",
    primary: "perte de puissance soudaine",
    secondary: ["voiture manque de puissance","moteur étouffe"],
    longTail: "perte puissance accélération causes",
    candidateQueries: [
      "perte de puissance soudaine",
      "voiture manque de puissance",
      "moteur étouffe",
      "perte puissance accélération causes",
      "voiture ne tire plus diesel",
      "perte de puissance soudaine : que faire",
      "comment perte de puissance soudaine",
      "voiture manque de puissance perte de puissance",
    ],
  },
  "plaquettes-frein-usure-signaux-a-ne-pas-ignorer": {
    intent: "informational",
    contentFormat: "Guide pratique — causes, que faire, retour atelier",
    primary: "plaquettes frein usées signaux",
    secondary: ["usure plaquettes frein","changer plaquettes frein"],
    longTail: "signes plaquettes frein usées",
    candidateQueries: [
      "plaquettes frein usées signaux",
      "usure plaquettes frein",
      "changer plaquettes frein",
      "signes plaquettes frein usées",
      "plaquettes frein bruit sifflement",
      "plaquettes frein usées signaux : que faire",
      "comment plaquettes frein usées signaux",
      "usure plaquettes frein plaquettes frein usées",
    ],
  },
  "pneus-ete-quand-passer-hiver-ile-de-france": {
    intent: "informational",
    contentFormat: "Guide entretien — fréquence et critères",
    primary: "pneus été quand passer hiver",
    secondary: ["pneus hiver Île-de-France","date pneus neige"],
    longTail: "quand monter pneus hiver 94",
    candidateQueries: [
      "pneus été quand passer hiver",
      "pneus hiver Île-de-France",
      "date pneus neige",
      "quand monter pneus hiver 94",
      "pneus été hiver date limite",
      "pneus été quand passer hiver ?",
      "pneus hiver Île-de-France pneus été quand",
      "pneus été quand passer hiver garage",
    ],
  },
  "preparer-voiture-hiver-conseils": {
    intent: "informational",
    contentFormat: "Guide pratique — causes, que faire, retour atelier",
    primary: "préparer voiture pour l'hiver",
    secondary: ["entretien voiture hiver","batterie froid hiver"],
    longTail: "checklist voiture hiver Ivry",
    candidateQueries: [
      "préparer voiture pour l'hiver",
      "entretien voiture hiver",
      "batterie froid hiver",
      "checklist voiture hiver Ivry",
      "conseils conduite hiver 94",
      "préparer voiture pour l'hiver : que faire",
      "comment préparer voiture pour l'hiver",
      "entretien voiture hiver préparer voiture pour",
    ],
  },
  "prix-changement-batterie-94": {
    intent: "commercial",
    contentFormat: "Comparatif prix — fourchette et facteurs",
    primary: "prix changement batterie 94",
    secondary: ["tarif batterie voiture","batterie auto prix posée"],
    longTail: "prix batterie voiture Val-de-Marne",
    candidateQueries: [
      "prix changement batterie 94",
      "tarif batterie voiture",
      "batterie auto prix posée",
      "prix batterie voiture Val-de-Marne",
      "changer batterie Ivry prix",
      "combien coûte changement batterie 94",
      "prix changement batterie 94 2026",
      "tarif batterie voiture prix changement batterie",
    ],
  },
  "prix-changement-embrayage-94": {
    intent: "commercial",
    contentFormat: "Comparatif prix — fourchette et facteurs",
    primary: "prix changement embrayage 94",
    secondary: ["tarif kit embrayage","embrayage voiture prix"],
    longTail: "prix embrayage complet 94",
    candidateQueries: [
      "prix changement embrayage 94",
      "tarif kit embrayage",
      "embrayage voiture prix",
      "prix embrayage complet 94",
      "changer embrayage Ivry devis",
      "combien coûte changement embrayage 94",
      "prix changement embrayage 94 2026",
      "tarif kit embrayage prix changement embrayage",
    ],
  },
  "prix-changement-plaquettes-frein-94": {
    intent: "commercial",
    contentFormat: "Comparatif prix — fourchette et facteurs",
    primary: "prix changement plaquettes frein 94",
    secondary: ["tarif plaquettes frein","frein avant prix"],
    longTail: "prix plaquettes frein posées 94",
    candidateQueries: [
      "prix changement plaquettes frein 94",
      "tarif plaquettes frein",
      "frein avant prix",
      "prix plaquettes frein posées 94",
      "changer plaquettes Ivry",
      "combien coûte changement plaquettes frein 94",
      "prix changement plaquettes frein 94 2026",
      "tarif plaquettes frein prix changement plaquettes",
    ],
  },
  "prix-changement-pneus-94": {
    intent: "commercial",
    contentFormat: "Comparatif prix — fourchette et facteurs",
    primary: "prix changement pneus 94",
    secondary: ["tarif montage pneus","pneus voiture prix"],
    longTail: "prix 4 pneus montés 94",
    candidateQueries: [
      "prix changement pneus 94",
      "tarif montage pneus",
      "pneus voiture prix",
      "prix 4 pneus montés 94",
      "changer pneus Ivry-sur-Seine",
      "combien coûte changement pneus 94",
      "prix changement pneus 94 2026",
      "tarif montage pneus prix changement pneus",
    ],
  },
  "prix-diagnostic-auto-94": {
    intent: "commercial",
    contentFormat: "Comparatif prix — fourchette et facteurs",
    primary: "prix diagnostic auto 94",
    secondary: ["tarif valise diagnostic","diagnostic OBD prix"],
    longTail: "prix diagnostic électronique Val-de-Marne",
    candidateQueries: [
      "prix diagnostic auto 94",
      "tarif valise diagnostic",
      "diagnostic OBD prix",
      "prix diagnostic électronique Val-de-Marne",
      "diagnostic voiture Ivry prix",
      "combien coûte diagnostic auto 94",
      "prix diagnostic auto 94 2026",
      "tarif valise diagnostic prix diagnostic auto",
    ],
  },
  "prix-geometrie-parallelisme-94": {
    intent: "commercial",
    contentFormat: "Comparatif prix — fourchette et facteurs",
    primary: "prix géométrie parallelisme 94",
    secondary: ["tarif parallelisme","alignement roues prix"],
    longTail: "prix géométrie 2 roues 94",
    candidateQueries: [
      "prix géométrie parallelisme 94",
      "tarif parallelisme",
      "alignement roues prix",
      "prix géométrie 2 roues 94",
      "parallelisme Ivry tarif",
      "combien coûte géométrie parallelisme 94",
      "prix géométrie parallelisme 94 2026",
      "tarif parallelisme prix géométrie parallelisme",
    ],
  },
  "prix-kit-distribution-94": {
    intent: "commercial",
    contentFormat: "Comparatif prix — fourchette et facteurs",
    primary: "prix kit distribution 94",
    secondary: ["tarif courroie distribution","distribution posée prix"],
    longTail: "prix changement distribution Val-de-Marne",
    candidateQueries: [
      "prix kit distribution 94",
      "tarif courroie distribution",
      "distribution posée prix",
      "prix changement distribution Val-de-Marne",
      "kit distribution Ivry",
      "combien coûte kit distribution 94",
      "prix kit distribution 94 2026",
      "tarif courroie distribution prix kit distribution",
    ],
  },
  "prix-pre-controle-technique-ivry": {
    intent: "transactional",
    contentFormat: "Comparatif prix — fourchette et facteurs",
    primary: "prix pré-contrôle technique Ivry",
    secondary: ["contre-visite CT prix","préparation contrôle technique"],
    longTail: "pré-contrôle technique Ivry-sur-Seine prix",
    candidateQueries: [
      "prix pré-contrôle technique Ivry",
      "contre-visite CT prix",
      "préparation contrôle technique",
      "pré-contrôle technique Ivry-sur-Seine prix",
      "éviter contre-visite CT 94",
      "combien coûte pré-contrôle technique Ivry",
      "prix pré-contrôle technique Ivry 2026",
      "contre-visite CT prix prix pré-contrôle technique",
    ],
  },
  "prix-recharge-climatisation-94": {
    intent: "commercial",
    contentFormat: "Comparatif prix — fourchette et facteurs",
    primary: "prix recharge climatisation 94",
    secondary: ["tarif recharge clim","gaz clim prix"],
    longTail: "prix recharge clim Val-de-Marne",
    candidateQueries: [
      "prix recharge climatisation 94",
      "tarif recharge clim",
      "gaz clim prix",
      "prix recharge clim Val-de-Marne",
      "recharge clim Ivry tarif",
      "combien coûte recharge climatisation 94",
      "prix recharge climatisation 94 2026",
      "tarif recharge clim prix recharge climatisation",
    ],
  },
  "quand-changer-pneus-usure-securite": {
    intent: "informational",
    contentFormat: "Guide entretien — fréquence et critères",
    primary: "quand changer pneus usure",
    secondary: ["témoin usure pneu","profondeur sculpture pneu"],
    longTail: "pneus usés limite légale sécurité",
    candidateQueries: [
      "quand changer pneus usure",
      "témoin usure pneu",
      "profondeur sculpture pneu",
      "pneus usés limite légale sécurité",
      "changer pneus avant hiver",
      "quand changer pneus usure ?",
      "témoin usure pneu quand changer pneus",
      "quand changer pneus usure garage",
    ],
  },
  "que-faire-apres-accident-carrosserie": {
    intent: "informational",
    contentFormat: "Guide pratique — causes, que faire, retour atelier",
    primary: "que faire après accident carrosserie",
    secondary: ["déclaration sinistre auto","réparation carrosserie accident"],
    longTail: "démarches après accrochage carrosserie",
    candidateQueries: [
      "que faire après accident carrosserie",
      "déclaration sinistre auto",
      "réparation carrosserie accident",
      "démarches après accrochage carrosserie",
      "carrosserie accident Ivry 94",
      "que faire après accident carrosserie ?",
      "déclaration sinistre auto que faire après",
      "que faire après accident carrosserie garage",
    ],
  },
  "rayure-carrosserie-quand-reparer": {
    intent: "informational",
    contentFormat: "Guide entretien — fréquence et critères",
    primary: "rayure carrosserie quand réparer",
    secondary: ["retouche rayure peinture","rayure profonde carrosserie"],
    longTail: "rayure portière réparer ou pas",
    candidateQueries: [
      "rayure carrosserie quand réparer",
      "retouche rayure peinture",
      "rayure profonde carrosserie",
      "rayure portière réparer ou pas",
      "rayure carrosserie prix Ivry",
      "rayure carrosserie quand réparer ?",
      "retouche rayure peinture rayure carrosserie quand",
      "rayure carrosserie quand réparer garage",
    ],
  },
  "revision-60000-km-checklist": {
    intent: "informational",
    contentFormat: "Checklist pratique",
    primary: "révision 60000 km checklist",
    secondary: ["entretien 60 000 km","grand entretien voiture"],
    longTail: "que faire révision 60000 km",
    candidateQueries: [
      "révision 60000 km checklist",
      "entretien 60 000 km",
      "grand entretien voiture",
      "que faire révision 60000 km",
      "révision 60 000 km prix",
      "révision 60000 km checklist : que faire",
      "comment révision 60000 km checklist",
      "entretien 60 000 km révision 60000 km",
    ],
  },
  "revision-constructeur-que-comprend-vraiment-service": {
    intent: "informational",
    contentFormat: "Guide pratique — causes, que faire, retour atelier",
    primary: "révision constructeur que comprend",
    secondary: ["entretien carnet constructeur","opérations révision officielle"],
    longTail: "contenu révision constructeur détail",
    candidateQueries: [
      "révision constructeur que comprend",
      "entretien carnet constructeur",
      "opérations révision officielle",
      "contenu révision constructeur détail",
      "révision réseau vs indépendant",
      "révision constructeur que comprend : que faire",
      "comment révision constructeur que comprend",
      "entretien carnet constructeur révision constructeur que",
    ],
  },
  "revision-garage-independant-garantie-constructeur": {
    intent: "informational",
    contentFormat: "Guide pratique — causes, que faire, retour atelier",
    primary: "révision garage indépendant garantie",
    secondary: ["entretien hors réseau garantie","Loi Hamon entretien auto"],
    longTail: "garage indépendant préserve garantie constructeur",
    candidateQueries: [
      "révision garage indépendant garantie",
      "entretien hors réseau garantie",
      "Loi Hamon entretien auto",
      "garage indépendant préserve garantie constructeur",
      "révision indépendant carnet",
      "révision garage indépendant garantie : que faire",
      "comment révision garage indépendant garantie",
      "entretien hors réseau garantie révision garage indépendant",
    ],
  },
  "revision-kilometrage-usage-urbain-94": {
    intent: "informational",
    contentFormat: "Guide pratique — causes, que faire, retour atelier",
    primary: "révision kilométrage usage urbain",
    secondary: ["entretien voiture ville","intervalle révision trajets courts"],
    longTail: "révision voiture usage urbain 94",
    candidateQueries: [
      "révision kilométrage usage urbain",
      "entretien voiture ville",
      "intervalle révision trajets courts",
      "révision voiture usage urbain 94",
      "entretien conduite ville Ivry",
      "révision kilométrage usage urbain : que faire",
      "comment révision kilométrage usage urbain",
      "entretien voiture ville révision kilométrage usage",
    ],
  },
  "rotule-biellette-direction-quand-changer": {
    intent: "informational",
    contentFormat: "Guide entretien — fréquence et critères",
    primary: "rotule direction quand changer",
    secondary: ["biellette direction usée","jeu direction rotule"],
    longTail: "rotule de direction symptômes usure",
    candidateQueries: [
      "rotule direction quand changer",
      "biellette direction usée",
      "jeu direction rotule",
      "rotule de direction symptômes usure",
      "changer rotule direction prix",
      "rotule direction quand changer ?",
      "biellette direction usée rotule direction quand",
      "rotule direction quand changer garage",
    ],
  },
  "roulement-roue-sifflement-symptomes": {
    intent: "informational",
    contentFormat: "Guide symptômes — signes, causes, que faire",
    primary: "roulement roue sifflement",
    secondary: ["roulement avant HS","bruit roue à vitesse"],
    longTail: "sifflement roulement roue causes",
    candidateQueries: [
      "roulement roue sifflement",
      "roulement avant HS",
      "bruit roue à vitesse",
      "sifflement roulement roue causes",
      "changer roulement roue prix",
      "roulement roue sifflement : que faire",
      "comment roulement roue sifflement",
      "roulement avant HS roulement roue sifflement",
    ],
  },
  "silentblocs-triangles-suspension-usure": {
    intent: "informational",
    contentFormat: "Guide pratique — causes, que faire, retour atelier",
    primary: "silentblocs triangles suspension usure",
    secondary: ["triangle suspension jeu","silentbloc HS symptômes"],
    longTail: "silentblocs usés bruit claquement",
    candidateQueries: [
      "silentblocs triangles suspension usure",
      "triangle suspension jeu",
      "silentbloc HS symptômes",
      "silentblocs usés bruit claquement",
      "changer triangles suspension",
      "silentblocs triangles suspension usure : que faire",
      "comment silentblocs triangles suspension usure",
      "triangle suspension jeu silentblocs triangles suspension",
    ],
  },
  "suppression-fap-controle-technique-2026": {
    intent: "informational",
    contentFormat: "Guide pratique — causes, que faire, retour atelier",
    primary: "suppression FAP contrôle technique 2026",
    secondary: ["FAP retiré CT","contre-visite FAP"],
    longTail: "suppression FAP légalité CT 2026",
    candidateQueries: [
      "suppression FAP contrôle technique 2026",
      "FAP retiré CT",
      "contre-visite FAP",
      "suppression FAP légalité CT 2026",
      "FAP supprimé refus CT",
      "suppression FAP contrôle technique 2026 : que faire",
      "comment suppression FAP contrôle technique 2026",
      "FAP retiré CT suppression FAP contrôle",
    ],
  },
  "surchauffe-moteur-que-faire": {
    intent: "informational",
    contentFormat: "Guide pratique — causes, que faire, retour atelier",
    primary: "surchauffe moteur que faire",
    secondary: ["voyant température allumé","moteur surchauffe urgence"],
    longTail: "surchauffe moteur conduite que faire",
    candidateQueries: [
      "surchauffe moteur que faire",
      "voyant température allumé",
      "moteur surchauffe urgence",
      "surchauffe moteur conduite que faire",
      "moteur qui chauffe arrêt",
      "surchauffe moteur que faire ?",
      "voyant température allumé surchauffe moteur que",
      "surchauffe moteur que faire garage",
    ],
  },
  "turbo-compresseur-symptomes-panne": {
    intent: "informational",
    contentFormat: "Guide symptômes — signes, causes, que faire",
    primary: "turbo compresseur symptômes panne",
    secondary: ["turbo HS diesel","perte puissance turbo"],
    longTail: "turbo qui siffle fume noir",
    candidateQueries: [
      "turbo compresseur symptômes panne",
      "turbo HS diesel",
      "perte puissance turbo",
      "turbo qui siffle fume noir",
      "changer turbo prix 94",
      "comment reconnaître turbo compresseur panne",
      "turbo compresseur symptômes panne causes",
      "turbo HS diesel turbo compresseur symptômes",
    ],
  },
  "vanne-egr-encrassee-symptomes": {
    intent: "informational",
    contentFormat: "Guide symptômes — signes, causes, que faire",
    primary: "vanne EGR encrassée symptômes",
    secondary: ["EGR bouchée diesel","nettoyage vanne EGR"],
    longTail: "vanne EGR encrassée perte puissance",
    candidateQueries: [
      "vanne EGR encrassée symptômes",
      "EGR bouchée diesel",
      "nettoyage vanne EGR",
      "vanne EGR encrassée perte puissance",
      "EGR à changer ou nettoyer",
      "comment reconnaître vanne EGR encrassée",
      "vanne EGR encrassée symptômes causes",
      "EGR bouchée diesel vanne EGR encrassée",
    ],
  },
  "vidange-boite-automatique-quand-faire": {
    intent: "informational",
    contentFormat: "Guide entretien — fréquence et critères",
    primary: "vidange boîte automatique quand faire",
    secondary: ["huile boîte auto intervalle","entretien boîte automatique"],
    longTail: "vidange boîte auto tous les combien km",
    candidateQueries: [
      "vidange boîte automatique quand faire",
      "huile boîte auto intervalle",
      "entretien boîte automatique",
      "vidange boîte auto tous les combien km",
      "boîte automatique huile noire",
      "vidange boîte automatique quand faire ?",
      "huile boîte auto intervalle vidange boîte automatique",
      "vidange boîte automatique quand faire garage",
    ],
  },
  "voiture-broute-acceleration-causes-94": {
    intent: "informational",
    contentFormat: "Guide pratique — causes, que faire, retour atelier",
    primary: "voiture broute à l'accélération",
    secondary: ["ratés accélération diesel","manque de puissance accélération"],
    longTail: "voiture broute en accélérant causes 94",
    candidateQueries: [
      "voiture broute à l'accélération",
      "ratés accélération diesel",
      "manque de puissance accélération",
      "voiture broute en accélérant causes 94",
      "broute moteur diesel EGR",
      "voiture broute à l'accélération : que faire",
      "comment voiture broute à l'accélération",
      "ratés accélération diesel voiture broute à",
    ],
  },
  "voiture-ne-demarre-pas-causes": {
    intent: "informational",
    contentFormat: "Guide pratique — causes, que faire, retour atelier",
    primary: "voiture ne démarre pas causes",
    secondary: ["panne démarrage auto","moteur ne tourne pas"],
    longTail: "voiture ne démarre plus le matin",
    candidateQueries: [
      "voiture ne démarre pas causes",
      "panne démarrage auto",
      "moteur ne tourne pas",
      "voiture ne démarre plus le matin",
      "diagnostic voiture ne démarre pas",
      "voiture ne démarre pas causes : que faire",
      "comment voiture ne démarre pas causes",
      "panne démarrage auto voiture ne démarre",
    ],
  },
  "voiture-occasion-checklist-achat": {
    intent: "informational",
    contentFormat: "Checklist pratique",
    primary: "checklist achat voiture occasion",
    secondary: ["contrôler voiture occasion","points vérifier occasion"],
    longTail: "liste vérification voiture d'occasion",
    candidateQueries: [
      "checklist achat voiture occasion",
      "contrôler voiture occasion",
      "points vérifier occasion",
      "liste vérification voiture d'occasion",
      "acheter occasion sans arnaque",
      "checklist achat voiture occasion : que faire",
      "comment checklist achat voiture occasion",
      "contrôler voiture occasion checklist achat voiture",
    ],
  },
  "volant-qui-vibre-causes": {
    intent: "informational",
    contentFormat: "Guide pratique — causes, que faire, retour atelier",
    primary: "volant qui vibre causes",
    secondary: ["vibration volant freinage","volant tremble vitesse"],
    longTail: "volant vibre à 100 km/h causes",
    candidateQueries: [
      "volant qui vibre causes",
      "vibration volant freinage",
      "volant tremble vitesse",
      "volant vibre à 100 km/h causes",
      "équilibrage roues vibration",
      "volant qui vibre causes : que faire",
      "comment volant qui vibre causes",
      "vibration volant freinage volant qui vibre",
    ],
  },
  "voyant-abs-allume-causes-conduite": {
    intent: "informational",
    contentFormat: "Guide symptômes — signes, causes, que faire",
    primary: "voyant ABS allumé causes",
    secondary: ["panne ABS voiture","conduire avec ABS allumé"],
    longTail: "voyant ABS fixe que faire",
    candidateQueries: [
      "voyant ABS allumé causes",
      "panne ABS voiture",
      "conduire avec ABS allumé",
      "voyant ABS fixe que faire",
      "capteur ABS défaillant",
      "voyant ABS allumé causes : que faire",
      "comment voyant ABS allumé causes",
      "panne ABS voiture voyant ABS allumé",
    ],
  },
  "voyant-moteur-allume-que-faire": {
    intent: "informational",
    contentFormat: "Guide symptômes — signes, causes, que faire",
    primary: "voyant moteur allumé que faire",
    secondary: ["diagnostic OBD voyant moteur","voyant moteur orange rouge"],
    longTail: "diagnostic voyant moteur Ivry 94",
    candidateQueries: [
      "voyant moteur allumé que faire",
      "diagnostic OBD voyant moteur",
      "voyant moteur orange rouge",
      "diagnostic voyant moteur Ivry 94",
      "peut-on rouler voyant moteur",
      "voyant moteur allumé que faire ?",
      "diagnostic OBD voyant moteur voyant moteur allumé",
      "voyant moteur allumé que faire garage",
    ],
  },
};
