/**
 * Hub /links/ — actions + réseaux (bio Instagram / TikTok / Snap).
 * Les href dynamiques (tel, WhatsApp, avis) sont résolus dans le template via site.*.
 */
module.exports = {
  actions: [
    {
      id: "site",
      label: "Site web",
      hint: "redkmotors.fr",
      href: "/",
      icon: "site",
      external: false,
      track: "click_link_hub",
      trackPos: "liens_site",
    },
    {
      id: "whatsapp",
      label: "WhatsApp",
      hint: "Message / photos",
      hrefKey: "whatsappUrl",
      icon: "whatsapp",
      external: true,
      track: "click_whatsapp",
      trackPos: "liens_hub",
    },
    {
      id: "call",
      label: "Appeler",
      hintKey: "phoneDisplay",
      hrefKey: "phoneTel",
      icon: "phone",
      external: false,
      track: "click_call",
      trackPos: "liens_hub",
    },
    {
      id: "contact",
      label: "Prendre rendez-vous",
      hint: "Adresse & formulaire",
      href: "/contact/",
      icon: "calendar",
      external: false,
      track: "click_link_hub",
      trackPos: "liens_contact",
    },
    {
      id: "google",
      label: "Avis Google",
      hintKey: "googleReviewsLabel",
      hrefKey: "googleReviewsMaps",
      icon: "google",
      external: true,
      track: "click_maps",
      trackPos: "liens_hub",
    },
  ],
  social: [
    {
      id: "instagram",
      label: "Instagram",
      hint: "@redkmotors",
      hrefKey: "instagramUrl",
      icon: "instagram",
      external: true,
      track: "click_social",
      trackPos: "liens_instagram",
    },
    {
      id: "tiktok",
      label: "TikTok",
      hint: "@redkmotors",
      hrefKey: "tiktokUrl",
      icon: "tiktok",
      external: true,
      track: "click_social",
      trackPos: "liens_tiktok",
    },
    {
      id: "facebook",
      label: "Facebook",
      hint: "RedKMotors",
      hrefKey: "facebookUrl",
      icon: "facebook",
      external: true,
      track: "click_social",
      trackPos: "liens_facebook",
    },
    {
      id: "youtube",
      label: "YouTube",
      hint: "@REDKMOTORS",
      hrefKey: "youtubeUrl",
      icon: "youtube",
      external: true,
      track: "click_social",
      trackPos: "liens_youtube",
    },
    {
      id: "snapchat",
      label: "Snapchat",
      hint: "@redkmotors",
      hrefKey: "snapchatUrl",
      icon: "snapchat",
      external: true,
      track: "click_social",
      trackPos: "liens_snapchat",
    },
  ],
};
