/**
 * Règles noindex centralisées — utilisées par base.njk et .eleventy.js (sitemap).
 */
module.exports = {
  prefixes: [
    "/garage-proche-",
    "/garage-vtc-",
    "/garage-taxi-",
    "/garage-chauffeur-prive-",
    "/garage-voiture-uber-",
    "/mecanicien-rapide-",
    "/mecanique-rapide-",
    "/diagnostic-auto-",
    "/revision-auto-",
    "/blog/tag/",
    "/devis-garage-",
    "/garage-urgence-",
    "/garage-flotte-entreprise-",
    "/garage-pneus-freins-",
    "/entretien-vehicule-vtc-",
    "/entretien-preventif-vtc-",
    "/entretien-voiture-professionnelle-",
    "/entretien-taxi-",
    "/changement-batterie-",
    "/changement-plaquettes-frein-",
    "/perte-puissance-voiture-",
    "/voiture-ne-demarre-plus-",
    "/consommation-carburant-elevee-",
    "/tremblement-volant-autoroute-",
    "/bruit-frein-voiture-",
    "/clim-voiture-ne-refroidit-plus-",
    "/reparation-climatisation-",
    "/changement-pneus-",
    "/revision-voiture-",
    "/voyant-abs-allume-",
    "/diagnostic-voyant-moteur-",
    "/vidange-rapide-",
    "/revision-rapide-",
    "/reparation-auto-paris-sud/",
    "/carrosserie-peinture-ivry/",
    "/lp-",
  ],
  /** URLs indexables malgré un prefix noindex (ex. /revision-auto-val-de-marne/). */
  indexablePaths: ["/revision-auto-val-de-marne/"],
};
